### ISSUE TITLE
How to cite this package

### ISSUE THREAD

**Issue by alexandermichels** [datamade/census#122]
If I were to use this package for research, how would you prefer that it be cited? From a quick search I didn't find any papers about this work or a [Zenodo](https://zenodo.org/) link. 

Thanks!

**Comment by fgregg** [comment]
thanks! i added a citation.cff for this project. here are some formats you can use:

Carbaugh, J., Gregg, F., & Contributors. (2022). census (Version 0.8.19) [Computer software]. https://github.com/datamade/census

@software{Carbaugh_census_2022,
author = {Carbaugh, Jeremy and Gregg, Forest and {Contributors}},
month = {7},
title = {{census}},
url = {https://github.com/datamade/census},
version = {0.8.19},
year = {2022}
}
