### ISSUE TITLE
2021 ACS 5 Year release not supported

### ISSUE THREAD

**Issue by JSzkup** [datamade/census#124]
Add support for the 2021 ACS release from Dec 8th: 
https://www.census.gov/programs-surveys/acs/news/data-releases.html

**Comment by nvenkatcivil** [comment]
You can modify in your local core.py. just add 2021 into that tuple. It will work, I hope next update that would be fixed.

**Comment by nvenkatcivil** [comment]
Now they updated against that issue. Now that 2021 is available . You may close this issue.
