### ISSUE TITLE
KeyError: Long

### ISSUE THREAD

**Issue by ProvidenceAdu** [datamade/census#144]
I am reporting an issue I am having with the Census Bureau API wrapper you help maintain. 

I had a script that has worked for the last 3 years without any problem. However, I am experiencing errors when I run the script today. 

I get a keyError: long whenever I execute the script. I have updated the wrapper to the latest release and I still experience the same problem. I also ran the script in a different Python environment (Google Collab) with the examples on your website, and the same error persists. 

![Key error2](https://github.com/datamade/census/assets/72041244/5a9c7fbf-c6b7-4635-a003-ecc125afba0a)
![Key Error](https://github.com/datamade/census/assets/72041244/44a3fe84-764b-47c3-95fd-2fd39cb65a7f)

**Comment by agentdanger** [comment]
https://github.com/datamade/census/pull/143/commits/dcd9330e22b5098951b5778f3045f92316087983  This pull request fixes the issue.  I made the change in the core.py file and it works for me.  Not sure when they'll accept the pull request and release a new package.

**Comment by agentdanger** [comment]
![image](https://github.com/datamade/census/assets/11284316/b61b8aa2-2541-46b0-95cc-2e15b1e9b5a9)
Adding "long" type into core.py

**Comment by pedrocamargo** [comment]
This seems to be fixed and the issue could be closed
