### ISSUE TITLE
Integer casting generates errors when API returns floats

### ISSUE THREAD

**Issue by prha** [datamade/census#45]
Commit 179c9d5cc74759772d191246599c4b19e549cfc3 is causing issues because the Census API is often returning floats for fields marked with predicateType 'int'.

It seems like the API is using the predicateType 'int' for all numerics.  Fields that represent a numeric mean across a geo have this mismatch:

```
$ curl https://api.census.gov/data/2015/acs5/variables/B23020_002E.json
{
  "name": "B23020_002E",
  "label": "Mean usual hours--!!Male",
  "concept": "B23020.  Mean Hours Worked in the Past 12 Months for Workers 16 to 64 Years",
  "predicateType": "int",
  "group": "N/A",
  "limit": 0,
  "validValues": [
  ]
}
```

The Census endpoint is returning a value of '41.4' here.

Not sure what the right behavior should be here, because I'm not sure what the value of commit of 179c9d5cc74759772d191246599c4b19e549cfc3 is, in the absence of consistent response handling.

**Comment by prha** [comment]
@fgregg, any ideas?

**Comment by fgregg** [comment]
Hi @prha 

I don't think I follow what you mean by

> I'm not sure what the value of commit of 179c9d5 is, in the absence of consistent response handling.

In any case, I think I'll adopt the strategy that @hrecht uses: https://github.com/hrecht/censusapi/blob/0a3e1a6bf7736f1708cc795ef2e3c10fe9a0279a/R/getcensus_functions.R#L30

**Comment by prha** [comment]
I was more saying that if we couldn't uniformly cast to numeric types, it's not that useful to have some numerics as strings and some as integers.  

Yeah, I like the approach... but I'm not that well-versed with R.  Do they have a generic numeric type?  What's the approach here?  We have to decide between int/float/str, right?

**Comment by fgregg** [comment]
the approach would to be cast everything to float

**Comment by prha** [comment]
SGTM, thanks.
