### ISSUE TITLE
Support for 2016 release in ACS5 and ACS1 without breaking releases prior to 2015

### ISSUE THREAD

**Issue by andytay** [datamade/census#47]
The 2012-2016 5-year ACS data is available through the Census API.

The Census Bureau is testing some changes with an alternate endpoint. Switching to this endpoint for ACS1 has broken functionality for years 2014 and prior.

Can we add support for 2016 ACS5 without breaking functionality for 2014 and prior? Can the same fix be applied to the ACS1 issue?

**Comment by fgregg** [comment]
I'm pretty sure this already supported. Could you give me an example of something that is not supported by this library?

**Comment by andytay** [comment]
`c = Census("MY_API_KEY")`
`c.acs1.state('B01001_004E', Census.ALL, year=2015)`

The above works because the Census Bureau has moved the 2015 data from the original endpoint from `'https://api.census.gov/data/%s/%s'` to  `'https://api.census.gov/data/%s/acs/%s'`

The Census Bureau has not yet moved the 2014 data endpoint. The below fails because it is trying to use the new endpoint. The same happens with years prior. Returns a 404 status in the CensusException error.

`c.acs1.state('B01001_004E', Census.ALL, year=2014)`

I'm happy to help fix but am a little stumped on how or if both endpoints can be supported with one class, relative to the year in question.

**Comment by fgregg** [comment]
Thank you. I should have a fix for this soon.

In the meantime, as a workaround you can do.

```python
c = Census("MY_API_KEY", year=2014)
c.acs1.state('B01001_004E', Census.ALL, year=2014)
```
