### ISSUE TITLE
Endpoint getting 404 on some years

### ISSUE THREAD

**Issue by brockfanning** [datamade/census#69]
Some queries are returning an HTML page (I believe from a 404 response) with the message "The requested resource is not available". Here is an example of a request that encounters this problem:

```
c = Census(my_api_key, year=2015)
results = c.acs5.state_county('C24010_041E', states.CA.fips, '037')
print(results)
```

But if I change the year to 2016, it works (returns results without any errors).

Hope this helps, let me know if there is any other info I can provide.

**Comment by chrismlarson** [comment]
I'm using `sf1` and am hitting the same issue. I contacted the census about it and they said:
> you will have to qualify the request with `dec` now. I.e.: `api.census.gov/data/2010/dec/sf1`

**Comment by rebeccajohnson88** [comment]
Hm thanks for information @chrismlarson . So does this mean that, for affected years, we can no longer use the `c.acs5.get` convenience wrapper? Thanks for any help.

**Comment by jtoh89** [comment]
@brockfanning I believe this is the issue: https://www.census.gov/data/developers/updates/api-format-changes--sf1-2010.html?eml=gd&utm_medium=email&utm_source=govdelivery

ACS endpoints have changed as well. I changed the If statement below to "year > 2009", and it started working fine.

`class ACSClient(Client):

    def _switch_endpoints(self, year):

        if year > **2015**:
            self.endpoint_url = 'https://api.census.gov/data/%s/acs/%s'
            self.definitions_url = 'https://api.census.gov/data/%s/acs/%s/variables.json'
            self.definition_url = 'https://api.census.gov/data/%s/acs/%s/variables/%s.json'
            self.groups_url = 'https://api.census.gov/data/%s/acs/%s/groups.json'
        else:
            self.endpoint_url = super(ACSClient, self).endpoint_url
            self.definitions_url = super(ACSClient, self).definitions_url
            self.definition_url = super(ACSClient, self).definition_url
            self.groups_url = super(ACSClient, self).groups_url`
