### ISSUE TITLE
You included a key with this request, however, it is not valid.

### ISSUE THREAD

**Issue by hexingren** [datamade/census#87]
When I was making an API request using the demo code, I received APIKeyError. When I clicked the link in the email to activate the key, it redirected me to an error page saying "You've attempted to validate an unknown key. If it has been more than 48 hours since you submitted your request for this API key then the request has been removed from the system. Please request a new key and activate it within 48 hours." Did someone meet the same issue, and maybe have figured it out?

**Comment by UGuntupalli** [comment]
@hexingren : 
         I was able to request a new key and got it without any problem. Perhaps try requesting a new API key using a different email id ?
