### ISSUE TITLE
Move to AIOHTTP (asyncio)

### ISSUE THREAD

**Issue by mclayton7** [datamade/census#88]
Would there be any interest in moving Census from Requests to python asyncio / AIOHTTP? I'm probably going to attempt to port this over so I can asynchronously dispatch multiple requests, unless there's a better way to optimize making a bunch of api requests. 

Would it be worth me putting it on a branch for you guys to take a look at?

**Comment by fgregg** [comment]
did you ever do this, would be happy to look at this approach
