### ISSUE TITLE
Can't Retrieve data at County level - Example please ? 

### ISSUE THREAD

**Issue by UGuntupalli** [datamade/census#91]
I am trying to get population using ACS1 at a county level or a zip code level if possible. 
ACS5 supports a method called zipcode which makes this possible as recommended here (#76). However, for my needs, I need this data through ACS1, so what I tried was :

```python 
   # Define a consensus class object to get population estimates 
   consensus_object = Census(api_key_census)

   # Get total population estimates 
   consensus_object.acs1.get(('NAME', 'B01003_001E'), {'for': 'county', 'in': 'county:36047, state:36'})
```
Trying to frame this similar to (#73). However, one thing that I am unable to figure out is: 

1. Does ACS1 support this ? 
2. If it does, can someone provide a working example ? 
3. Assuming, there is no way to do this, can anyone suggest alternatives with this or a different package ?

**Comment by lucaluca** [comment]
ACS1 does not support ZIP codes. https://github.com/datamade/census/issues/76#issuecomment-641349763

You can retrieve population data for decently large counties through ACS1. Only about 800 counties are provided in ACS1. 

```python
>>> client = Census(os.environ.get('CENSUS_API_KEY'))
>>> results = client.acs1.state_county(['NAME', 'B01003_001E'], '*', '*')
>>> len(results)
838
```
