### ISSUE TITLE
Not working for census subject tables

### ISSUE THREAD

**Issue by patwater** [datamade/census#93]
Hi this nifty little package works nicely though seems to default to the census detail tables and it is unclear how to call the subject tables using one of the methods. For example the following query breaks: 

```
c.acs5.get(('NAME', 'S0801_C01_046E'), 
           geo = {'for': 'county:*',
                 'in': 'state:06'})
```

Note the subject tables require the word SUBJECT as part of the API query as follows: 

https://api.census.gov/data/2018/acs/acs1/subject?get=NAME,S0801_C01_046E&for=county:*&in=state:06

Compare to another query like so:

https://api.census.gov/data/2018/acs/acs1/?get=NAME&for=state:*

**Comment by patwater** [comment]
Thanks! Note the following rent burden table DP is having issues: 

c.acs5st.get('DP04_0109E', {'for': 'state:06'})

**Comment by jeancochrane** [comment]
It looks like `DP04_0109E` comes from a data profile table, have you tried the [`acs5dp` method](https://github.com/datamade/census#datasets)?
