### ISSUE TITLE
Enable 2019 1- and 5-year estimates

### ISSUE THREAD

**Issue by jeancochrane** [datamade/census#95]
2019 1-year estimates are out, and 5-year estimates should be available 12/10. Let's update the `years` attributes of all the clients to make sure these estimates are available when ready.

**Comment by fgregg** [comment]
sound good!

**Comment by fgregg** [comment]
the 2019 1-year estimates are available now.

**Comment by tjk911** [comment]
Is this working already - I'm having issues with 2019 1-year estimates still.
